---
- hosts: all
  gather_facts: false
  connection: local
  vars_files:
    - vault/vcenter_secrets.yml
  vars:
    vm_name: testvm_2
    vm_template: template_centos7_tiny
    notes: "Deployed with ansible"
    vm_datacenter: "DC1"
    vm_folder: "/vm"
    vm_datastore: datastore1
  tasks:
  # Get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
  # Create a VM from a template
  - name: create the VM
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      datacenter: "{{ vm_datacenter }}"
      folder: "{{ vm_folder }}"
      name: "{{ vm_name }}"
      state: poweredon
      guest_id: centos7_64Guest
      annotation: "{{ notes }} - {{ creationdate }}"
      disk:
      - size_gb: 6
        type: thin
        datastore: "{{ vm_datastore }}"
      hardware:
        memory_mb: 1024
        num_cpus: 1
      customization:
        dns_servers:
        - 172.116.113.2
        - 172.116.113.3
        domain : vsphere.local
        hostname: "{{ vm_name }}"
      template: "{{ vm_template }}"
      # wait_for_ip_address: It's necessary to have vmware-tools already installed
      wait_for_ip_address: yes