---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vault/vcenter_vars.yml
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: testvm_2
      template: centOS7_minimal
      datacenter: DC1
      folder: /vm
      state: poweredon
      # wait_for_ip_address: yes